package main

import (
	"example/usecase"
	"github.com/joho/godotenv"
	"github.com/rs/cors"
	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"
	"log"
	"net/http"
	"os"

	"example/gen/eliza/v1/elizav1connect" // generated by protoc-gen-connect-go
)

func main() {
	address := "0.0.0.0:8000"
	err := godotenv.Load(".env")
	if err != nil {
		log.Fatal("Error loading .env file")
	}
	openaiKey := os.Getenv("OPENAI_KEY")
	if openaiKey == "" {
		log.Fatal("OPENAI_KEY environment variable must be set")
	}

	eliza := usecase.NewElizaServer(openaiKey)

	mux := http.NewServeMux()
	path, handler := elizav1connect.NewElizaServiceHandler(eliza)
	mux.Handle(path, handler)

	corsHandler := cors.AllowAll().Handler(h2c.NewHandler(mux, &http2.Server{}))
	err = http.ListenAndServe(
		address,
		corsHandler,
	)
	if err != nil {
		panic(err)
	}
}
